Robustness: Align and improve error messages

diff --git a/bin/pipethrough1 b/bin/pipethrough1
--- a/bin/pipethrough1
+++ b/bin/pipethrough1
@@ -177,9 +177,11 @@ if [ -n "$messageSubject" ]; then
     fi
     case "$warnOn" in
 	0)  if [ "$check" = ':' ]; then
-		echo >&2 "ERROR: --warn-unless-change cannot be specified when change checking isn't enabled"
+		echo "ERROR: --warn-unless-change cannot be specified when change checking isn't enabled"
+		echo
+		printUsage "$0"
 		exit 2
-	    fi
+	    fi >&2
 	    : ${messageOnSuccess="Warning: $messageSubject did not change %q"}
 	    ;;
 	*)  if [ "$check" = ':' ]; then
@@ -211,9 +213,11 @@ if [ ${#simpleCommand[@]} -gt 0 ]; then
     fi
 fi
 if [ ${#commands[@]} -eq 0 ]; then
-    echo >&2 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    echo
+    printUsage "$0"
     exit 2
-fi
+fi >&2
 
 
 
