pipethrough: Refactoring: Minor: Change degenerate switch statement to if...else
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/pipethrough b/bin/pipethrough
--- a/bin/pipethrough
+++ b/bin/pipethrough
@@ -239,30 +239,25 @@ if [ -n "$messageSubject" ]; then
     esac
 fi
 
-case "$1" in
-    --)
+if [ "$1" = -- ]; then
+    shift
+    while [ $# -gt 0 -a "$1" != '--' ]
+    do
+	simpleCommand+=("$1")
 	shift
-	while [ $# -gt 0 -a "$1" != '--' ]
-	do
-	    simpleCommand+=("$1")
-	    shift
-	done
-	if [ $# -eq 0 ]; then
-	    echo 'ERROR: -- SIMPLECOMMAND [ARGUMENT ...] must be concluded with --'; echo; printUsage "$0"
-	    exit 2
-	fi >&2
+    done
+    if [ $# -eq 0 ]; then
+	echo 'ERROR: -- SIMPLECOMMAND [ARGUMENT ...] must be concluded with --'; echo; printUsage "$0"
+	exit 2
+    fi >&2
+    shift
+elif [ -n "$commandArgumentNum" ]; then
+    for (( i = 0; i < commandArgumentNum; i++ ))
+    do
+	simpleCommand+=("$1")
 	shift
-	;;
-    *)
-	if [ -n "$commandArgumentNum" ]; then
-	    for (( i = 0; i < commandArgumentNum; i++ ))
-	    do
-		simpleCommand+=("$1")
-		shift
-	    done
-	fi
-	;;
-esac
+    done
+fi
 if [ ${#simpleCommand[@]} -gt 0 ]; then
     # Combine --command and SIMPLECOMMAND; need to quote SIMPLECOMMAND to
     # undo the effects of eval.
