ENH: Support -- COMMAND -- (inspired from the canonical separator between options and arguments) and \; COMMAND \; (inspired by find -exec) in addition to a quoted (single-argument) COMMAND; quoting may be cumbersome
Support --help.

diff --git a/bin/pipethrough b/bin/pipethrough
--- a/bin/pipethrough
+++ b/bin/pipethrough
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 ###############################################################################
 ##
 # FILE: 	pipethrough
@@ -18,6 +18,12 @@
 # REVISION	DATE		REMARKS
 #	015	14-Jun-2016	Use eval() instead of $SHELL, printf instead of
 #				echo.
+#				ENH: Support -- COMMAND -- (inspired from the
+#				canonical separator between options and
+#				arguments) and \; COMMAND \; (inspired by find
+#				-exec) in addition to a quoted (single-argument)
+#				COMMAND; quoting may be cumbersome.
+#				Support --help.
 #	014	12-Apr-2016	Use mktemp, $SHELL.
 #	013	26-May-2009	Replaced Korn Shell'ish 'print -R' with 'echo'.
 #	0.12	26-Sep-2006	Simplified print command.
@@ -28,17 +34,52 @@
 #	0.01	01-Jan-2004	file creation
 ###############################################################################
 
+printUsage()
+{
+    cat <<HELPTEXT
+Usage:
+    $(basename "$1") "COMMAND [ARGUMENTS ...]" FILE [, ...]
+    $(basename "$1") -- COMMAND [ARGUMENTS ...] -- FILE [, ...]
+    $(basename "$1") \; COMMAND [ARGUMENTS ...] \; FILE [, ...]
+HELPTEXT
+}
+
+case "$1" in
+    --help|-h|-\?)	shift; printUsage "$0"; exit 0;;
+esac
 if [ $# -lt 2 ]; then
-    echo >&2 "Usage: $(basename -- "$0") COMMAND FILE [, ...]"
+    printUsage "$0"
     exit 2
 fi
 
-command=$1
-shift
+case "$1" in
+    \;|--)
+	separator=$1
+	shift
+	typeset -a command
+	while [ "$1" != "$separator" ]
+	do
+	    command+=("$1")
+	    shift
+	done
+	shift
 
+	if [ ${#command[@]} -eq 0 ]; then
+	    echo >&2 "ERROR: No COMMAND specified"
+	    printUsage "$0"
+	    exit 2
+	fi
+	;;
+    *)
+	eval "typeset -a command=($1)"
+	shift
+	;;
+esac
+
+####D echo "**** ${command[0]}"; echo "**** ${command[1]}"; echo "**** ${command[2]}"; exit
 for file
 do
     tmpFile=$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || echo "${TEMP:-/tmp}/$(basename -- "$0").$$")
     printf >&2 '%s\n' "${command} '${file}'"
-    eval "${command} '${file}'" > "${tmpFile}" && mv -f "${tmpFile}" "${file}"
+    "${command[@]}" "$file" > "$tmpFile" && mv -f "$tmpFile" "$file"
 done
