Add test variants for pipethrough1 and adapt it, too

diff --git a/bin/pipethrough1 b/bin/pipethrough1
--- a/bin/pipethrough1
+++ b/bin/pipethrough1
@@ -38,8 +38,8 @@
 printShortUsage()
 {
     printf 'Usage: %q %s\n' $(basename "$1") '[-v|--verbose] [-p|--piped] [-b|--backup EXT] [--test-only|(--diff-only|--diff [--diff-cmd CMD] [--diff-options OPT])] [--error-unless-change|--error-on-change] [--message-on-change MSG] [--message-on-success MSG] [--message-on-failure MSG] [--message-on-error MSG] ([--message-subject SUBJECT] [--warn-on-change|--warn-unless-change]) [-?|-h|--help] ...'
-    printf 'Usage: %q %s\n' $(basename "$1") '... COMMAND [ARGUMENTS ...] FILE'
-    printf 'Usage: %q %s\n' $(basename "$1") '-c|--command "COMMANDLINE [{}] ..." FILE'
+    printf 'Usage: %q %s\n' $(basename "$1") '[...] -c|--command "COMMANDLINE [{}] ..." [-c ...] FILE'
+    printf 'Usage: %q %s\n' $(basename "$1") '[...] SIMPLECOMMAND [ARGUMENTS ...] FILE'
 }
 printUsage()
 {
@@ -108,7 +108,7 @@ commandArgumentNum=
 diffCommand=diff; type -t colordiff >/dev/null && diffCommand=colordiff # Highlight diff output if available.
 diffOptions=-u
 isPiped=
-verbosePiped=
+commandJoiner=';'
 isVerbose=
 warnOn=
 unset messageOnChange
@@ -120,8 +120,9 @@ while [ $# -ne 0 ]
 do
     case "$1" in
 	--help|-h|-\?)	shift; printLongUsage "$0"; exit 0;;
+	--command|-c)	shift; commands+=(${commands:+$commandJoiner} "$1"); isNeedEval=t; shift;;
 	--verbose|-v)	shift; isVerbose=t;;
-	--piped|-p)	shift; isPiped=t; verbosePiped='< ';;
+	--piped|-p)	shift; isPiped=t; commandJoiner='|';;
 	--backup|-b)	shift; backupExtension="$1"; shift;;
 	--test-only)	shift; action=testChanges;;
 	--diff-only)	shift; action=diffChanges;;
@@ -162,10 +163,8 @@ do
 	*)		break;;
     esac
 done
-[ $# -eq 0 ] && { printUsage "$0" >&2; exit 2; }
-if [ $# -lt 2 ]; then
-    echo >&2 "ERROR: No FILE to pipe."
-    printUsage "$0"
+if [ $# -eq 0 ]; then
+    printUsage "$0" >&2
     exit 2
 fi
 if [ "$messageSubject" ]; then
@@ -192,8 +191,23 @@ if [ "$messageSubject" ]; then
     esac
 fi
 
-typeset -a command=("${@:1:$(($#-1))}")
+typeset -a simpleCommand=("${@:1:$(($#-1))}")
 typeset file="${!#}"
+if [ ${#simpleCommand[@]} -gt 0 ]; then
+    if [ "$isNeedEval" ]; then
+	# Combine --command and SIMPLECOMMAND; need to quote SIMPLECOMMAND to
+	# undo the effects of eval.
+	printf -v quotedSimpleCommand '%q ' "${simpleCommand[@]}"
+	quotedSimpleCommand="${quotedSimpleCommand% }"
+	commands+=(${commands:+$commandJoiner} "${quotedSimpleCommand//\\\{\\\}/\{\}}")	# %q escapes {}, we don't want that to have it interpolated later.
+    else
+	commands=("${simpleCommand[@]}")
+    fi
+fi
+if [ ${#commands[@]} -eq 0 ]; then
+    echo >&2 'ERROR: No COMMAND(s) specified; need to pass -c|--command "COMMANDLINE", or SIMPLECOMMAND.'
+    exit 2
+fi
 
 
 
@@ -262,16 +276,23 @@ checkError()
 
 
 
-####D echo "**** ${command[0]}"; echo "**** ${command[1]}"; echo "**** ${command[2]}"; exit
+####D echo "**** $isNeedEval ${commands[0]}"; echo "**** ${commands[1]}"; echo "**** ${commands[2]}"; exit
 tmpFile=$(mktemp --tmpdir "$(basename -- "$0")-XXXXXX" 2>/dev/null || echo "${TEMP:-/tmp}/$(basename -- "$0").$$")
 
-typeset -a interpolatedCommand=("${command[@]//\{\}/$file}")
-typeset -a f=("$file")
-[ "${interpolatedCommand[*]}" = "${command[*]}" ] || f=()
+interpolatedFile="$file"; [ "$isNeedEval" ] && printf -v interpolatedFile '%q' "$file"
+typeset -a interpolatedCommands=("${commands[@]//\{\}/$interpolatedFile}")
+typeset -a f=("$interpolatedFile")
+[ "${interpolatedCommands[*]}" = "${commands[*]}" ] || f=()
 
 if [ "$isVerbose" ]; then
-    printf >&2 '%q ' "${command[@]}"
-    printf >&2 "${verbosePiped}%q\n" "${file}"
+    quoter='%q'; [ "$isNeedEval" ] && quoter='%s'
+    if [ "$isPiped" ]; then
+	[ ${#f[@]} -eq 0 -a -n "$isPiped" ] && f=("$interpolatedFile")
+	printf "< $quoter " "${f[@]}"
+	f=()
+    fi
+    printf -v verboseCommand "$quoter " "${interpolatedCommands[@]}" "${f[@]}"
+    printf >&2 "%s\n" "${verboseCommand% }"
 fi
 
 if [ "$backupExtension" ]; then
@@ -279,14 +300,22 @@ if [ "$backupExtension" ]; then
 fi
 
 if [ "$isPiped" ]; then
-    # Note: Use $interpolatedCommand instead of $command here; any {} would
+    # Note: Use $interpolatedCommands instead of $commands here; any {} would
     # be expanded in there, which might only make sense for weird corner
     # cases, so why not. Another argument is that we simply always log
-    # $interpolatedCommand with --verbose, so the action should be
+    # $interpolatedCommands with --verbose, so the action should be
     # consistent with that.
-    "${interpolatedCommand[@]}" < "$file" > "$tmpFile"
+    if [ "$isNeedEval" ]; then
+	< "$file" eval "${interpolatedCommands[@]}" > "$tmpFile"
+    else
+	< "$file" "${interpolatedCommands[@]}" > "$tmpFile"
+    fi
 else
-    "${interpolatedCommand[@]}" "${f[@]}" > "$tmpFile"
+    if [ "$isNeedEval" ]; then
+	eval "${interpolatedCommands[@]}" "${f[@]}" > "$tmpFile"
+    else
+	"${interpolatedCommands[@]}" "${f[@]}" > "$tmpFile"
+    fi
 fi && \
     $check "$tmpFile" "$file" && \
     $action "$tmpFile" "$file" && \
