Robustness: Detect missing second --, too
The added --exec prints an error when running out of arguments before the concluding ;, add the same for the existing -- SIMPLECOMMAND ...  --, too. (And tests for both.)

diff --git a/bin/pipethrough b/bin/pipethrough
--- a/bin/pipethrough
+++ b/bin/pipethrough
@@ -234,6 +234,10 @@ case "$1" in
 	    simpleCommand+=("$1")
 	    shift
 	done
+	if [ $# -eq 0 ]; then
+	    echo 'ERROR: -- SIMPLECOMMAND [ARGUMENTS ...] must be concluded with --!'; echo; printUsage "$0"
+	    exit 2
+	fi >&2
 	shift
 	;;
     *)
