pipethrough: CHG: Disallow -- SIMPLECOMMAND -- after --command or --exec
This is confusing, and not necessary; the --exec is fully equivalent.
This allows the disambiguation of FILE arguments that start with two dashes (and could therefore confuse the command-line argument parsing).

System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/pipethrough b/bin/pipethrough
--- a/bin/pipethrough
+++ b/bin/pipethrough
@@ -26,8 +26,8 @@ fileMarker="$PIPETHROUGH_FILE_MARKER"; unset PIPETHROUGH_FILE_MARKER
 printShortUsage()
 {
     printf 'Usage: %q %s\n' "$(basename "$1")" '[-v|--verbose] [-P|--no-pass-file|-p|--piped] [-b|--backup EXT|--backup-command writeorig|writebackup|writeOrigOrBackup] [--test-only|(--diff-only|--diff [--diff-cmd CMD] [--diff-options OPT])] [--abort-unless-change|--abort-on-change] [--message-on-change MSG] [--message-on-success MSG] [--message-on-failure MSG] [--message-on-abort MSG] [--message-subject SUBJECT [--warn-on-change|--warn-unless-change]] [-?|-h|--help] ...'
-    printf 'Usage: %q %s\n' "$(basename "$1")" "[...] -c|--command \"COMMANDLINE [...] [${fileMarker}] [...]\" [-c ...] [FILE ...]"
-    printf 'Usage: %q %s\n' "$(basename "$1")" "[...] --exec SIMPLECOMMAND [ARGUMENT ...] [${fileMarker}] [ARGUMENT ...] $PIPETHROUGH_EXEC_END [--exec ...] [FILE ...]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[...] -c|--command \"COMMANDLINE [...] [${fileMarker}] [...]\" [-c ...] [--] [FILE ...]"
+    printf 'Usage: %q %s\n' "$(basename "$1")" "[...] --exec SIMPLECOMMAND [ARGUMENT ...] [${fileMarker}] [ARGUMENT ...] $PIPETHROUGH_EXEC_END [--exec ...] [--] [FILE ...]"
     printf 'Usage: %q %s\n' "$(basename "$1")" "[...] -- SIMPLECOMMAND [ARGUMENT ...] [${fileMarker}] [ARGUMENT ...] -- [FILE ...]"
     printf 'Usage: %q %s\n' "$(basename "$1")" "[...] -n|--command-arguments N SIMPLECOMMAND [ARGUMENT ...] [${fileMarker}] [ARGUMENT ...] [FILE ...]"
 }
@@ -241,16 +241,18 @@ fi
 
 if [ "$1" = -- ]; then
     shift
-    while [ $# -gt 0 -a "$1" != '--' ]
-    do
-	simpleCommand+=("$1")
+    if [ -z "$commands" ]; then
+	while [ $# -gt 0 -a "$1" != '--' ]
+	do
+	    simpleCommand+=("$1")
+	    shift
+	done
+	if [ $# -eq 0 ]; then
+	    echo 'ERROR: -- SIMPLECOMMAND [ARGUMENT ...] must be concluded with --'; echo; printUsage "$0"
+	    exit 2
+	fi >&2
 	shift
-    done
-    if [ $# -eq 0 ]; then
-	echo 'ERROR: -- SIMPLECOMMAND [ARGUMENT ...] must be concluded with --'; echo; printUsage "$0"
-	exit 2
-    fi >&2
-    shift
+    fi
 elif [ -n "$commandArgumentNum" ]; then
     for (( i = 0; i < commandArgumentNum; i++ ))
     do
