processEachFile: ENH: Allow progress reporting via --progress SINK

diff --git a/bin/processEachFile b/bin/processEachFile
--- a/bin/processEachFile
+++ b/bin/processEachFile
@@ -16,12 +16,15 @@
 # @(#)pipethrough	$Id$	pipes
 ###############################################################################
 
+: ${PROCESSEACHFILE_FILE_WHAT=file}
 : ${PIPETHROUGH_FILE_MARKER='{}'}
 fileMarker="$PIPETHROUGH_FILE_MARKER"; unset PIPETHROUGH_FILE_MARKER
 
+hasProgressNotification=; type -t progressNotification >/dev/null && hasProgressNotification=t
+
 printShortUsage()
 {
-    printf 'Usage: %q %s\n' $(basename "$1") '[-v|--verbose] [--delta-via backup|copy|fileAge|fileSize|cksum|sha256sum] [-b|--backup EXT|--backup-command writeorig|writebackup|writeOrigOrBackup] [--diff [--diff-cmd CMD] [--diff-options OPT]] [--abort-unless-change|--abort-on-change] [--message-on-change MSG] [--message-on-success MSG] [--message-on-failure MSG] [--message-on-abort MSG] [--message-subject SUBJECT [--warn-on-change|--warn-unless-change]] [-?|-h|--help] ...'
+    printf 'Usage: %q %s%s %s\n' $(basename "$1") '[-v|--verbose]' "${hasProgressNotification:+ [--progress SINK]}" '[--delta-via backup|copy|fileAge|fileSize|cksum|sha256sum] [-b|--backup EXT|--backup-command writeorig|writebackup|writeOrigOrBackup] [--diff [--diff-cmd CMD] [--diff-options OPT]] [--abort-unless-change|--abort-on-change] [--message-on-change MSG] [--message-on-success MSG] [--message-on-failure MSG] [--message-on-abort MSG] [--message-subject SUBJECT [--warn-on-change|--warn-unless-change]] [-?|-h|--help] ...'
     printf 'Usage: %q %s\n' $(basename "$1") "[...] -c|--command \"COMMANDLINE [${fileMarker}] ...\" [-c ...] FILE [, ...]"
     printf 'Usage: %q %s\n' $(basename "$1") "[...] --exec SIMPLECOMMAND [${fileMarker}] [ARGUMENTS ...] ; FILE [, ...]"
     printf 'Usage: %q %s\n' $(basename "$1") "[...] -- SIMPLECOMMAND [${fileMarker}] [ARGUMENTS ...] -- FILE [, ...]"
@@ -50,7 +53,9 @@ HELPDESCRIPTION
     printShortUsage "$1"
     echo
     cat <<HELPTEXT
-    --verbose|-v	    Show each executed command on stderr.
+    --verbose|-v	    Show each executed command on stderr.${hasProgressNotification:+
+    --progress SINK	    Report the current FILE through one of the SINKs of
+			    the progressNotification command.}
     --delta-via backup|copy|fileAge|fileSize|cksum|sha256sum
 			    Determine whether the file has changed through the
 			    passed algorithm. This can be any command that takes
@@ -138,6 +143,7 @@ diffCommand=diff; [ -t 1 ] && type -t colordiff >/dev/null && diffCommand=colord
 diffOptions=-u
 commandJoiner=';'
 isVerbose=
+progressSink=
 warnOn=
 unset messageOnChange
 unset messageOnSuccess
@@ -162,6 +168,7 @@ do
 			shift
 			;;
 	--verbose|-v)	shift; isVerbose=t;;
+	--progress)	shift; progressSink="$1"; shift;;
 	--backup|-b)	shift; backupExtension="${1:?}"; shift; backupCommand=backupToExtension; delta=backup;;
 	--backup-command)
 			shift; backupCommand="$1"; shift; delta=backup;;
@@ -401,6 +408,18 @@ if [ $# -eq 0 ]; then
     exit 2
 fi >&2
 
+if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
+    exec 3> >(progressNotification --to "$progressSink" ${PROCESSEACHFILE_FILE_WHAT:+--prepend-count "${PROCESSEACHFILE_FILE_WHAT}"} --count-to $# 2>/dev/null)
+
+    reportProgress()
+    {
+	trap 'reportProgress() { :; }; trap PIPE' PIPE
+	printf '%s\n' "$*" >&3 2>/dev/null  # Silence "printf: write error: Broken pipe"
+    }
+else
+    reportProgress() { :; }
+fi
+
 exitStatus=0
 for file
 do
@@ -448,6 +467,7 @@ do
 	copyDigest=''
     fi
 
+    reportProgress "$file"
     isChange=
     if [ "$isNeedEval" ]; then
 	eval "${interpolatedCommands[@]}" "${f[@]}"
