Style: Use -n for non-booleans

diff --git a/bin/processEachFile b/bin/processEachFile
--- a/bin/processEachFile
+++ b/bin/processEachFile
@@ -184,7 +184,7 @@ do
 				abortOn=1
 				;;
 	--message-on-change)	shift
-				[ "$1" -a "$check" = ':' ] && check=checkChanges
+				[ -n "$1" -a "$check" = ':' ] && check=checkChanges
 				messageOnChange="$1"
 				shift
 				;;
@@ -204,7 +204,7 @@ if [ $# -eq 0 ]; then
     printUsage "$0" >&2
     exit 2
 fi
-if [ "$messageSubject" ]; then
+if [ -n "$messageSubject" ]; then
     if [ ! "${messageOnChange+t}" ]; then
 	case "$warnOn" in
 	    1)	messageOnChange="Warning: $messageSubject changed %q";;
@@ -249,7 +249,7 @@ case "$1" in
 	shift
 	;;
     *)
-	if [ "$commandArgumentNum" ]; then
+	if [ -n "$commandArgumentNum" ]; then
 	    for (( i = 0; i < commandArgumentNum; i++ ))
 	    do
 		simpleCommand+=("$1")
@@ -279,7 +279,7 @@ fi
 
 message()
 {
-    if [ "$1" ]; then
+    if [ -n "$1" ]; then
 	printf "$1\\n" "$2"
     fi
 }
@@ -342,7 +342,7 @@ checkAbort()
     local copyFilespec="${1?}"; shift
     local copyDigest="${1?}"; shift
     local file="${1:?}"; shift
-    [ "$abortOn" ] || return 0
+    [ -n "$abortOn" ] || return 0
 
     case "$delta" in
 	'') echo >&2 'ASSERT: $delta must not be empty when checking.'; exit 3;;
@@ -372,7 +372,7 @@ checkAbort()
 
 ####D echo "**** $isNeedEval ${commands[0]}"; echo "**** ${commands[1]}"; echo "**** ${commands[2]}"; exit
 if [ $# -eq 0 ]; then
-    echo >&2 "ERROR: No FILEs to pipe."
+    echo >&2 "ERROR: No FILEs to process."
     printUsage "$0"
     exit 2
 fi
