Refactoring: Extract pipelineCommandName()
And use that abbreviated one in the "empty dir" error message, except when debugging is enabled (so the directory is kept); then, print the full interpolated commandline to enable the user to troubleshoot this.

diff --git a/bin/tempdirPipe b/bin/tempdirPipe
--- a/bin/tempdirPipe
+++ b/bin/tempdirPipe
@@ -131,13 +131,18 @@ getTempDir()
 [ "${DEBUG:-}" ] || trap 'rm -rf -- "${tempDirspecs[@]}" 2>/dev/null' EXIT
 
 
+pipelineCommandName()
+{
+    commandName --eval --no-interpreter --undefined "${1:?}" "${1:?}"
+}
+
 if [ "$hasProgressNotification" ] && [ -n "$progressSink" ]; then
     exec 3> >(progressNotification --to "$progressSink" --prepend-count 'command' --count-to "${#commands[@]}" 2>/dev/null)
 
     reportProgress()
     {
 	trap 'reportProgress() { :; }; trap PIPE' PIPE
-	printf '%s\n' "$(commandName --eval --no-interpreter --undefined "${1:?}" "${1:?}")" >&3 2>/dev/null  # Silence "printf: write error: Broken pipe"
+	printf '%s\n' "$(pipelineCommandName "${1:?}")" >&3 2>/dev/null  # Silence "printf: write error: Broken pipe"
     }
 else
     reportProgress() { :; }
@@ -152,7 +157,7 @@ evaluate()
 withHeader()
 {
     local isFirst=; [ $2 -eq 1 ] && isFirst=t
-    header ${isFirst:+--first} "$(commandName --eval --no-interpreter --undefined "${1:?}" "${1:?}")"
+    header ${isFirst:+--first} "$(pipelineCommandName "${1:?}")"
 
     eval "${1:?}"
 }
@@ -198,7 +203,7 @@ do
     $executor "$interpolatedCommand" "$((${#commands[@]} - $#))" || exit $?
 
     if [ ! "$isRunIfEmpty" ] && emptydir -- "$outputDirspec"; then
-	printf >&2 'ERROR: No output from $ %s\n' "$pipelineCommand"
+	printf >&2 'ERROR: No output from $ %s\n' "$([ "$DEBUG" ] && printf %s "$interpolatedCommand" || pipelineCommandName "$interpolatedCommand")"
 	exit 99
     fi
 
