Debugging: Adapt: Replace DEBUG switch statements with new shell-debugging toolset
System-info: Ubuntu 20.04.6 LTS, x86_64
Platform-info: bash 5.0.17(1)-release, Bats 1.10.0

diff --git a/bin/tempdirPipe b/bin/tempdirPipe
--- a/bin/tempdirPipe
+++ b/bin/tempdirPipe
@@ -160,7 +160,7 @@ getTempDir()
 	|| { dirspec="${TMPDIR:-/tmp}/$(basename -- "$0").$$$RANDOM"; mkdir -p -- "$dirspec" && printf %s "$dirspec"; } \
 	|| return 3
 }
-[ "${DEBUG:-}" ] || trap 'rm -rf -- "${tempDirspecs[@]}" 2>/dev/null' EXIT
+! ${DEBUG:+debugenabled --invert-match --} ${DEBUG:-:} || trap 'rm -rf -- "${tempDirspecs[@]}" 2>/dev/null' EXIT
 
 
 pipelineCommandName()
@@ -255,7 +255,10 @@ do
     $executor "$interpolatedCommand" "$((${#commands[@]} - $#))" || exit $?
 
     if [ ! "$isRunIfEmpty" ] && emptydir -- "$outputDirspec"; then
-	printf >&2 'ERROR: No output from $ %s\n' "$([ "$DEBUG" ] && printf %s "$interpolatedCommand" || pipelineCommandName "$interpolatedCommand")"
+	printf >&2 'ERROR: No output from $ %s\n' "$(
+	    ${DEBUG:+debugcustom printf %s "$interpolatedCommand"}
+	    ${DEBUG:+debugcustom --invert-match --} pipelineCommandName "$interpolatedCommand"
+	)"
 	exit 99
     fi
 
